Temporary solution for "TypeError: allureJsCommons.AllureConfig is not a constructor" error to lock on "allure-js-commons" version that does not have an error
isaaceindhoven/testcafe-reporter-allure pull request #106
Opened 2021-09-01 12:48 UTC by lpelypenko

We started to get an error "TypeError: allureJsCommons.AllureConfig is not a constructor" that fails our builds and makes library unusable for us.

Until the issue is fixed in https://github.com/allure-framework/allure-js-commons/issues/48 I would like to propose this temporary solution to lock on  "allure-js-commons": "2.0.0-beta.8" that is still backward compatible.

Removing `^` should lock npm on specific version, while using "^2.0.0-beta.8" currently intstalls minor versions that incompatible with current implementation of `testcafe-reporter-allure`

The error is also reported in https://github.com/isaaceindhoven/testcafe-reporter-allure/issues/102.

2021-09-03 12:29 UTC, vanhoofmaarten requested changes
Hi @lpelypenko,

Thank you very much for the thorough description and your time to submit this PR.

Some feedback:
1. Could you split up the changes into separate branches?
	1. "TypeError: allureJsCommons.AllureConfig is not a constructor" error
	2. Implemented skip reason to show in categories
1. I've noticed a few linting errors are still present in the provided code. This is an error on our side. The safeguards (lint-staged / GitHub Action) system does a lint and autofix, without committing the changed auto-fixed files. This is now fixed in the develop branch. Could you merge the updated develop branch in this one and run 'npm install'?

Moving the `allureJsCommons.AllureConfig is not a constructor` fix seems to be a relatively quick change?

2021-09-05 09:58 UTC, lpelypenko commented
Hi @vanhoofmaarten,

I really appreciate your fast reply. 
Thank you for suggestion to split changes in 2 separate commits. This makes more sense to me too. I also had it in mind but initially made a mistake pushing all in my `develop` branch. 
I have already pushed temporary fix for type error into this branch https://github.com/isaaceindhoven/testcafe-reporter-allure/pull/108

Will create a separate pull with small feature implementation shortly.

2021-09-05 10:31 UTC, lpelypenko commented on docs/usage/metadata.md
> +![Example of the metadata for passed test.](../images/passed.png)
Thank you for the suggestion. I have added more details in `docs/usage/metadata.md` and also wrote more explanation on how skip reason can benefit `Categories` view if user used custom allure categories filter. 
Moved changed in https://github.com/isaaceindhoven/testcafe-reporter-allure/pull/109

2021-09-05 13:08 UTC, lpelypenko commented
I think this MR should be closed because I split changes in two MRs:
https://github.com/isaaceindhoven/testcafe-reporter-allure/pull/108
https://github.com/isaaceindhoven/testcafe-reporter-allure/pull/109

2021-09-05 13:08 UTC, closed without merging